# ASP.NET Core (.NET Framework)

# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
  
#- job: 'IntegrationTests'
 # pool:
  #  name: IntegrationTestPool  # name of the pool to run this job in

  #steps:
  #- task: DotNetCoreCLI@2
   # inputs:
    #  command: 'build'
     # projects: '$(solution)'
     # configuration: '$(buildConfiguration)'

  #- task: Bash@3
   # inputs:
    #  targetType: 'inline'
     # script: 'az login --identity'
     # noProfile: false
     # noRc: false

#  - task: DotNetCoreCLI@2
 #   inputs:
  #    command: 'test'
   #   projects: '**/Diagnostics.Tests.Integration.*.csproj'
    #  arguments: '--configuration $(buildConfiguration)'
    
    
- job: 'UnitTestAndPublish'
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk step'
    inputs:
      packageType: sdk
      version: 3.1.x
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: NuGetAuthenticate@0
    inputs:
      nuGetServiceConnections: 'AzureGenevaMonitoring'

  - task: DotNetCoreCLI@2
    displayName: 'Restore Packages'
    inputs:
      command: 'restore'
      projects: '**/Diagnostics.Tests.csproj'
      feedsToUse: 'select'
      vstsFeed: 'b2430cf7-78c0-440a-aa4a-a25665c5778e'

  - task: DotNetCoreCLI@2
    displayName: 'Run Tests'
    inputs:
      command: 'test'
      projects: '**/Diagnostics.Tests.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: "Publish"
    inputs:
      command: publish
      publishWebProjects: True
      arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: True

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: backend-drop1

- job: 'BuildLanguageServer'
  pool:
    vmImage: 'ubuntu-1604'

  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'backend-drop1'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: '$(System.ArtifactsDirectory)/Diagnostics.RuntimeHost.zip'
      destinationFolder: '$(Agent.BuildDirectory)/applensdlls'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Agent.BuildDirectory)/applensdlls'
      Contents: |
        Diagnostics.DataProviders.dll
        Diagnostics.Logger.dll
        Diagnostics.ModelsAndUtils.dll
        Diagnostics.Scripts.dll
        Kusto.Data.dll
      TargetFolder: '$(Agent.BuildDirectory)/src/LanguageServer/workspace/customdlls'
      OverWrite: true
      cleanDestinationFolder: true
      overwriteExistingFiles: false
  
  - task: Docker@2
    inputs:
      containerRegistry: 'LanguageServerRegistry'
      repository: 'containerappstest.azurecr.io/langserv'
      command: 'buildAndPush'
      Dockerfile: '$(Agent.BuildDirectory)/**/Dockerfile'
      buildContext: '$(Agent.BuildDirectory)/src/LanguageServer'